### ISSUE TITLE
Chrome extension does not open on first attempt

### ISSUE THREAD

**Issue by asbjornenge** [robertknight/passcards#62]
I do this:

```
* Click the extension
* Enter password
-- Extension says *Syncing...* but still shows master password input --
-- Entering password again leads to same result --
* Click menu and select "Switch Store"
* Select the same store I had already selected (only one I have)
* Enter password again
-- Now it works
```

Not a huge issue, but starting to get annoying enough for me to report it :stuck_out_tongue: 

I'm using Chrome 42.0.2311.90 (64-bit) on Linux, Passcards 0.3.935.

Thanks!

**Comment by robertknight** [comment]
I've been able to reproduce this as well. Work distracted me from Passcards improvements these past few weeks but I hope to get back to it soon.

**Comment by asbjornenge** [comment]
Thanks! I look forward to it :wink: :+1:

**Comment by nekojira** [comment]
It happens to me as well (Ubuntu 15.04 and 15.10, Chrome latest, keychain in dropbox). It started happening after a sync problem. It keeps syncing but it will always report '9 items not synced' kinda of message.

**Comment by asbjornenge** [comment]
Disabling and re-enabling the extension under chrome://extensions seems to have solved the problem for me!

**Comment by asbjornenge** [comment]
Apparently it get's into a broken state again if I ever type the wrong master password :stuck_out_tongue:

**Comment by robertknight** [comment]
This can be reproduced as follows:

1. Install Chrome extension
2. Open extension, add your 1Password/Passcards store, enter master password
3. Dismiss the extension popup and wait for the extension to auto-lock (the default timeout is two minutes)
4. Open the extension popup again, re-enter master password

Two issues occur in step 4:
1. The password field is not focused when the popup opens, so you have to manually focus it
2. The unlock view does not slide out of the way after entering the correct password

Syncing with your store in Dropbox following unlock does happen, so the issue is with the unlock pane not sliding out of the way, rather than the vault not unlocking. Disabling the slide effect in a development build avoids the problem - so something is happening with `ReactCSSTransitionGroup`.

**Comment by robertknight** [comment]
Possibly related to 61f465484b2998b472f4e82911ce86eff3ca5a9a
