### ISSUE TITLE
Can't sign in: 'atob is not a function'

### ISSUE THREAD

**Issue by unfulvio** [robertknight/passcards#64]
I can't sign in and unlock the valut, when I enter my 1 password, passcards displays a message in the black label at the bottom saying 'atob is not a function' - tried to restart the extension or chrome altogether to no avail. Running Chrome 47.0.2526.106 (64-bit) on Ubuntu 15.10.

**Comment by robertknight** [comment]
This is happening due to https://github.com/node-browser-compat/atob/pull/5

**Comment by robertknight** [comment]
Thanks for the bug report. A fixed version of the extension is now live in the Chrome store.

**Comment by unfulvio** [comment]
Hey Rob, thanks for the prompt fix

but I think there's still an issue; I restarted Chrome with the updated extension, now I get a different error:

`Failed to execute 'atob' on 'Window': the string to be decoded is not correctly encoded. Hint: it all started in 2008` (sic)

the `Hint: it all started in 2008` part doesn't always appear

I can't yet open Passcards, tried also to enable/disable the extension and switch store

**Comment by robertknight** [comment]
Is this a 1Password store created originally with Passcards or with the official 1Password app and were you able to use a previous version of Passcards successfully?

Can you try to reproduce the issue with a new store/vault created using the same software as your original one and if that doesn't open in Passcards, send me a copy of the folder containing the store's data, including the "encryptionKeys.js" file?

**Comment by unfulvio** [comment]
The store was created with 1password software on a Windows machine years ago and stored on Dropbox ever since. 

I tried to remove Passcards from Chrome (uninstall the extension) and restart the browser. I was prompted to authorize again Passcards again with Dropbox, but I got then the same error as before when unlocking it.

I can't perform the test you ask because I'm unable to select a new store I just created because Passcards scans Dropbox and retrieves all the stores located there but also the backups; there's no scrolling or way for me to reach the new file.

My stores (vaults) open correctly in 1Password using Wine.

**Comment by robertknight** [comment]
Thanks for the info @unfulvio . I was able to reproduce the problem with a vault created using 1Password for Windows, which adds some junk data to the end of the encrypted password data in "encryptionKeys.js".

I fixed the original issue in this bug report but I've opened a separate issue at https://github.com/robertknight/passcards/issues/66 to track the issue with vaults created using 1Password for Windows. Please subscribe to that issue for updates.

The commandline version of Passcards (installable via `npm install -g passcards`) does work with Windows vaults because that happens to be more lenient about ignoring said junk data.
